apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watterssu-portfolio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/watersu916/watterssu-gitops.git'
    targetRevision: main
    path: k3s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
